version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=urlshort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  web:
    build: .
    command: bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db