# Generated by Django 3.2 on 2021-05-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_urldata_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urldata',
            options={'verbose_name': 'Url', 'verbose_name_plural': 'Urls'},
        ),
    ]
