# Generated by Django 3.2 on 2021-05-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_alter_urldata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='slug',
            field=models.IntegerField(default=0),
        ),
    ]
