# Generated by Django 3.2 on 2021-05-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_alter_urldata_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='slug',
            new_name='new_url',
        ),
    ]
